# Generated by Django 5.1.1 on 2024-10-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_br',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_global',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_tr',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='product id'),
        ),
    ]
