# Generated by Django 5.1.1 on 2024-10-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price_br_product_price_global_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_br',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_global',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_tr',
        ),
    ]
