# Generated by Django 5.1.1 on 2024-12-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_file_file_type_alter_file_file_alter_file_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'audio'), (2, 'video'), (3, 'pdf'), (4, 'image')], default=1, verbose_name='file type'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
