# Generated by Django 5.1.1 on 2025-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_file_file_type_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=70, verbose_name='title'),
        ),
    ]
